<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <RootNamespace>Mujoco.Nodes</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\GSNodeGraphCore\GSNodeGraphCore\GSNodeGraphCore.csproj" />
    <ProjectReference Include="..\..\..\geometry3Sharp\geometry3Sharp.csproj" />
  </ItemGroup>


	<!--- This will copy the mujoco.dll the output folder for this project and also any dependent project -->
	<ItemGroup>
		<Content Include="mujoco\bin\mujoco.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>mujoco.dll</TargetPath>
		</Content>
		<Content Include="mujoco\bin\simulate.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>simulate.exe</TargetPath>
		</Content>
	</ItemGroup>


	<!-- Copy output .dll, .pdb, json files to a fixed directory (top-level \x64\(Debug|Release) here...maybe this could be configurable?) -->
	<Target Name="PublishDlls" AfterTargets="AfterBuild">
		<!-- Copy command docs: https://learn.microsoft.com/en-us/visualstudio/msbuild/copy-task?view=vs-2022 -->
		<ItemGroup>
			<BuildOutputFiles Include="$(OutDir)\MujocoNodeLibrary.*" />
			<BuildOutputFiles Include="$(OutDir)\mujoco.dll" />
			<BuildOutputFiles Include="$(OutDir)\simulate.exe" />
		</ItemGroup>
		<Copy SourceFiles="@(BuildOutputFiles)" DestinationFolder="$(SolutionDir)\GSNodeGraphEditor\AdditionalNodeLibraries\MujocoNodeLibrary" SkipUnchangedFiles="true" />
	</Target>


</Project>
