<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Meshmixer.Nodes</RootNamespace>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="mm\mmapi.exp" />
    <None Remove="mm\mmapi.lib" />
    <None Remove="mm\mmapi.pdb" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\GSNodeGraphCore\GSNodeGraphCore\GSNodeGraphCore.csproj" />
    <ProjectReference Include="..\..\..\GSNodeGraphEngine\GSNodeGraph\GSNodeGraph.csproj" />
    <ProjectReference Include="..\..\..\geometry3Sharp\geometry3Sharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="mm\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="mmapi_csharp">
      <HintPath>mm\mmapi_csharp.dll</HintPath>
    </Reference>
  </ItemGroup>

	<!--- This will copy the mmapi.dll the output folder for this project and also any dependent project -->
	<ItemGroup>
		<Content Include="mm\mmapi.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>mmapi.dll</TargetPath>
		</Content>
	</ItemGroup>


  <!-- Copy output .dll, .pdb, json files to a fixed directory (top-level \x64\(Debug|Release) here...maybe this could be configurable?) -->
  <Target Name="PublishDlls" AfterTargets="AfterBuild">
    <!-- Copy command docs: https://learn.microsoft.com/en-us/visualstudio/msbuild/copy-task?view=vs-2022 -->
	<ItemGroup>
		<BuildOutputFiles Include="$(OutDir)\MeshmixerNodeLibrary.*" />
		<BuildOutputFiles Include="$(OutDir)\mmapi*.*" />
	</ItemGroup> 
    <Copy SourceFiles="@(BuildOutputFiles)" DestinationFolder="$(SolutionDir)\GSNodeGraphEditor\AdditionalNodeLibraries\MeshmixerNodeLibrary" SkipUnchangedFiles="true" />
  </Target>


</Project>
