<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Debug_NoPolyscope</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug_NoPolyscope|AnyCPU'">
    <DefineConstants>$(DefineConstants);NOPOLYSCOPE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="2.88.8" />
    <PackageReference Include="SkiaSharp.Extended" Version="2.0.0" />
    <PackageReference Include="SkiaSharp.Svg" Version="1.60.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\GSNodeGraphCore\GSNodeGraphCore\GSNodeGraphCore.csproj" />
    <ProjectReference Include="..\..\GSNodeGraphEngine\GSNodeGraphCodeNodesLibrary\GSNodeGraphCodeNodesLibrary.csproj" />
    <ProjectReference Include="..\..\GSNodeGraphEngine\GSNodeGraphCoreLibrary\GSNodeGraphCoreLibrary.csproj" />
    <ProjectReference Include="..\..\GSNodeGraphEngine\GSNodeGraphGeometryLibrary\GSNodeGraphGeometryLibrary.csproj" />
    <ProjectReference Include="..\..\GSNodeGraphEngine\GSNodeGraphImageLibrary\GSNodeGraphImageLibrary.csproj" />
    <ProjectReference Include="..\..\GSNodeGraphEngine\GSNodeGraph\GSNodeGraph.csproj" />
    <ProjectReference Include="..\..\GSNodeGraphEngine\GSPythonNodesLibrary\GSPythonNodesLibrary.csproj" />
    <ProjectReference Include="..\..\GSNodeGraphEngine\GSPythonUtils\GSPythonUtils.csproj" />
    <ProjectReference Include="..\..\geometry3Sharp\geometry3Sharp.csproj" />
    <ProjectReference Include="..\GSUI\GSUI.csproj" />
  </ItemGroup>

</Project>
