<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>Assets\main_icon_v3.ico</ApplicationIcon>
    <AssemblyName>GSGraphEditor</AssemblyName>
    <RootNamespace>GSGraphEditor</RootNamespace>
    <Title>Gradientspace Graph Editor</Title>
    <Company>GradientSpace Corp.</Company>
    <Authors>rms80</Authors>
    <Copyright>Copyright Gradientspace Corp. All Rights Reserved.</Copyright>
    <PackageProjectUrl>https://www.gradientspace.com/gsgraphdemo</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.2" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.2" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.2">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DerivativeEngine\GSNodeGraph\GSNodeGraph.csproj" />
    <ProjectReference Include="..\..\geometry3Sharp\geometry3Sharp.csproj" />
    <ProjectReference Include="..\GSNodeEditor\GSNodeEditor.csproj" />
    <ProjectReference Include="..\NodeLibraries\GenAINodeLibrary\GenAINodeLibrary.csproj" />
  </ItemGroup>


  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>


  <ItemGroup>
    <Content Include="Assets\favicon.ico" />
    <Content Include="Assets\main_icon_v3.ico" />
  </ItemGroup>


  <ItemGroup>
    <Folder Include="Dialogs\" />
  </ItemGroup>

    <!-- Build node libraries without establishing direct link... -->
	<!-- TODO: make a parent project that builds all of them... -->
    <Target Name="BuildMeshmixer" AfterTargets="Build">
	    <MSBuild Projects="$(ProjectDir)..\NodeLibraries\MeshmixerNodeLibrary\MeshmixerNodeLibrary.csproj" Targets="Build" Properties="Configuration=$(Configuration);Platform=$(Platform)" />
    </Target>	
	
</Project>
